---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - ../group_vars/all

  tasks:
  - name: Add ESXi Host(s)
    vsphere_guest:
      vcenter_hostname: "{{ esxi_ip }}" # ip address of hypervisor
      esxi:
        datacenter: ha-datacenter
        hostname: "{{ esxi_hostname }}" # name shown in hypervisor console
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      validate_certs: no

      guest: '{{ item.key }}'
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: no
        mem.hotadd:  no
        notes: This is a test VM
        #folder: MyFolder
      vm_disk:
        disk1:
          size_gb: '{{ item.value.hd_gb }}'
          type: thin
          datastore: '{{ item.value.vdisk_datastore }}'
          # VMs can be put into folders. The value given here is either the full path
          # to the folder (e.g. production/customerA/lamp) or just the last component
          # of the path (e.g. lamp):
          folder: '{{ item.value.vdisk_folder }}'
      vm_nic:
        nic1:
          type: vmxnet3
          network: '{{ item.value.network_name }}'
          network_type: standard
      vm_hardware:
        memory_mb: '{{ item.value.memory_mb }}'
        num_cpus: '{{ item.value.num_cpus }}'
        osid: ubuntu64Guest
        scsi: paravirtual
        vm_cdrom:
          type: "iso"
          iso_path: "{{ item.value.iso_datastore }}/{{ item.value.iso_path }}"
    with_dict: "{{ vms }}"
