---
- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - ../group_vars/all
  - ../group_vars/{{ env }}

  tasks:
    - name: "Launch TestOne"
      include: tasks/launch.yml
      vars:
        item: { key: testOne, value: "{{ vms.testOne }}" }
      tags:
        - all
        - testOne

    - name: "Launch TestTwo"
      include: tasks/launch.yml
      vars:
        item: { key: testTwo, value: "{{ vms.testTwo }}" }
      tags:
        - all
        - testTwo

    - name: "Launch Ansible"
      include: tasks/launch.yml
      vars:
        item: { key: ansible, value: "{{ vms.ansible }}" }
      tags:
        - all
        - ansible

    - name: "Deploy Ansible"
      include: tasks/deploy/ansible.yml
      delegate_to: "{{ env }}-ansible.john"
      vars:
        item: { key: ansible, value: "{{ vms.ansible }}" }
      tags:
        - all
        - ansible
